import Head from "next/head";
import { Button, Group, Stack } from "@mantine/core";
import { LoginModal } from "@/templates/Login/LoginModal";
import useGlobalState from "@/hooks/useGlobalState";
import { MODAL_OPEN } from "@/store/ui/ui.events";
import { AppModals } from "@/helper/constants";
import { SignupModal } from "@/templates/Signup/SignupModal";
import { ContactModal } from "@/templates/Contact/ContactModal";
import { WikiLink } from "@/components/Link";
import { PageTemplate } from "@/components/PageTemplate/PageTemplate";
import { ChangePasswordModal } from "@/templates/ChangePassword/ChangePasswordModal";

export default function Home() {
  const { dispatch } = useGlobalState();
  const handleLogin = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Login,
      },
    });
  };
  const handleSignup = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Signup,
      },
    });
  };
  const handleContact = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Contact,
      },
    });
  };
  const handleChangePassword = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.ChangePassword,
      },
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTemplate>
        <Stack>
          <Group>
            <Button onClick={handleLogin}>Test Login</Button>
            <Button onClick={handleSignup}>Test Sign up</Button>
            <Button onClick={handleContact}>Test Contact</Button>
            <Button onClick={handleChangePassword}>Test change password</Button>
          </Group>
          <WikiLink href="/auth/login">Login</WikiLink>
          <WikiLink href="/auth/signup">Sign up</WikiLink>
          <WikiLink href="/auth/email_verification">
            email verification
          </WikiLink>
          <WikiLink href="/auth/forgotten_password">
            forgotten password
          </WikiLink>
          <WikiLink href="/auth/reset_password">reset password</WikiLink>
          <WikiLink href="/auth/onboarding">on boarding</WikiLink>
          <WikiLink href="/profile">Profile page</WikiLink>
          <WikiLink href="/settings">Settings page</WikiLink>
        </Stack>
        <LoginModal />
        <SignupModal />
        <ContactModal />
        <ChangePasswordModal />
      </PageTemplate>
    </>
  );
}
