import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@mantine/core";
import BottomNavigation from "@/components/BottomNavigation/BottomNavigation";
import SideBar from "@/components/Sidebar/Sidebar";
import { WikiNavigation } from "@/components/Navigation";
import { LoginModal } from "@/templates/Login/LoginModal";
import useGlobalState from "@/hooks/useGlobalState";
import { MODAL_OPEN } from "@/store/ui/ui.events";
import { AppModals } from "@/helper/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { dispatch } = useGlobalState();
  const handleLogin = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Login,
      },
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <WikiNavigation />
          <BottomNavigation />
          <SideBar />
          <Button onClick={handleLogin}>Test Login</Button>
          <LoginModal />
        </main>
      </div>
    </>
  );
}
