import Head from "next/head";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@mantine/core";
import BottomNavigation from "@/components/BottomNavigation/BottomNavigation";
import SideBar from "@/components/Sidebar/Sidebar";
import { WikiNavigation } from "@/components/Navigation";
import { LoginModal } from "@/templates/Login/LoginModal";
import useGlobalState from "@/hooks/useGlobalState";
import { MODAL_OPEN } from "@/store/ui/ui.events";
import { AppModals } from "@/helper/constants";
import { SignupModal } from "@/templates/Signup/SignupModal";
import { ContactModal } from "@/templates/Contact/ContactModal";

const geistSans = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function Home() {
  const { dispatch } = useGlobalState();
  const handleLogin = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Login,
      },
    });
  };
  const handleSignup = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Signup,
      },
    });
  };
  const handleContact = () => {
    dispatch({
      type: MODAL_OPEN,
      payload: {
        id: AppModals.Contact,
      },
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} `}>
        <main className={styles.main}>
          <WikiNavigation />
          <BottomNavigation />
          <SideBar />
          <Button onClick={handleLogin}>Test Login</Button>
          <Button onClick={handleSignup}>Test Sign up</Button>
          <Button onClick={handleContact}>Test Contact</Button>
          <LoginModal />
          <SignupModal />
          <ContactModal />
        </main>
      </div>
    </>
  );
}
