import express from "express";
import cors from "cors";
import path from "path";
import formatResponse from "./middleware/formatResponse";
import morganMiddleware from "./middleware/logMiddleware";
import session from "express-session";
import { CORS_WHITELIST, MAX_AGE, TOKEN_SECRET } from "./helper/constants";
import errorHandlingMiddleware from "./middleware/errorHandlingMiddleware";
import { authSessionOptions } from "./session";
import { apiRoutes } from "./api";

export const app = express();
app.set("views", path.join(__dirname, "../views"));
app.set("view engine", "pug");
app.use(express.static(path.join(__dirname, "../public")));
app.use(express.json({ limit: "50mb" }));
app.use(session(authSessionOptions));
app.use(cors({ origin: CORS_WHITELIST, credentials: true }));
app.use(morganMiddleware);
app.use(formatResponse);
app.use("/", ...apiRoutes);
app.use(errorHandlingMiddleware);
