import { ReactNode } from "react";
import styles from "./PageComponent.module.css";
import { Container } from "@mantine/core";
import Head from "next/head";
import { appName } from "@/helper/constants";
export const PageComponent = (props: {
  withPadding?: boolean;
  children: ReactNode;
  title?: string;
  description?: string;
}) => {
  const classes = `${styles.main} ${props.withPadding ? styles.padding : ""}`;
  return (
    <>
      <Head>
        <title>
          {appName} - {props.title}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={classes}>
        <Container h={"100%"}>{props.children}</Container>
      </section>
    </>
  );
};
